### ISSUE TITLE
[Scope] Add button to see apps from a developer

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#60]
In the app preview page, it would be nice to have a button "More Apps from this developer" or something with better wording that lists all apps made by that developer. A nice improvement over the official ubuntu store.

**Comment by bhdouglass** [comment]
That functionality is already there, if you click on the author's name or the "More apps by X" (under the screenshots) it will take you too the search page with a list of all apps by that developer. Like this: https://uappexplorer.com/apps?q=author:Brian%20Douglass&sort=relevance

Since that wasn't immediately obvious to you maybe a change is in order.

**Comment by krnekhelesh** [comment]
Erm I don't see it still :P. Could it be that you haven't updated the scope in the store? I dont see "More apps by X" nor am I able to click on the author's name.

**Comment by krnekhelesh** [comment]
![scope](https://cloud.githubusercontent.com/assets/761845/9803394/5f884d6e-5822-11e5-8a3a-a9d3a784e113.png)

**Comment by bhdouglass** [comment]
Oh, the scope! I thought you were talking about the website (I should read your titles). Yes, much agreeded. I'll get that in there.

**Comment by krnekhelesh** [comment]
I should report the bugs against the right project ;) .. my bad.

**Comment by bhdouglass** [comment]
Haha its all good :)

**Comment by bhdouglass** [comment]
I just uploaded v1.5 which has a "more apps by" button, enjoy!

**Comment by krnekhelesh** [comment]
Woohoo thnx. u rock!
